### ISSUE TITLE
NEE uses protocol eddy covariance

### ISSUE THREAD

**Issue by mobb** [DataONEorg/sem-prov-ontologies#11]
add protocol to NEE, ECSO_00000014, 
eddy covariance, ECSO_00000091

**Comment by Olson87** [comment]
These already have objectProperty 'measuresUsingProtocol', should it be changed to 'usesProtocol' ?

**Comment by mobb** [comment]
I missed that. lets leave as is for now. That object property is probably in OBOE, so we won't change it.
