### ISSUE TITLE
Clean up URIs used in salmon ontology

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-ontologies#119]
We noticed some of the terms in the salmon ontology don't consistently pad their OBO-style URIs to 8 digits (e.g., 001234 when they should be 00001234). Mark is going to do this cleanup but I'll manage this issue with progress.

**Comment by amoeba** [comment]
A list of all the URIs we've already used is over at https://github.com/DataONEorg/sem-prov-ontologies/issues/120#issuecomment-973684643.

**Comment by mbjones** [comment]
All of the 5 and 6 digit URIs were converted to 8 digit, and the SALMON_alignment.ttl file was created to map between them. Also, the redirects were restructured to automatically redirect 5 and 6 digit identifiers to their 8 digit counterparts. So, completed in salmon-0.3.2
