### ISSUE TITLE
Fix RDF validation errors

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-ontologies#39]
Hey @stevenchong 	I mentioned some of these on Slack but here's the full output I get from the Java library we use across DataONE to process RDF. I get these when trying to load `ECSO8.owl` from the latest GitHub version on the branch you're working on:

```
[ WARN] 2019-02-01 21:40:15,466 (org.dataone.cn.indexer.annotation.OntologyModelService:init:84) Reading http://purl.dataone.org/ontologies/observation/d1-ECSO.owl
[ WARN] 2019-02-01 21:40:15,611 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,651 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Margaret O'Brien, http://orcid.org/0000-0002-1693-8322' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,681 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Margaret O'Brien, http://orcid.org/0000-0002-1693-8322' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,684 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Margaret O'Brien, http://orcid.org/0000-0002-1693-8322' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,686 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Margaret O'Brien, http://orcid.org/0000-0002-1693-8322' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,711 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,751 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,753 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,770 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Adapted from
https://en.wikipedia.org/wiki/Dissolved_organic_carbon' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,788 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Adapted from
https://en.wikipedia.org/wiki/Biomass_(ecology)' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,801 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Physics definition: https://en.wikipedia.org/wiki/Area_density
General defiintion: https://www.google.com/#q=define+density' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,951 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,952 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
[ WARN] 2019-02-01 21:40:15,952 (org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger:logWarning:95) Lexical form 'Sara Lafia, http://orcid.org/0000-0002-5896-7295' not valid for datatype XSD anyURI
```

Do you think you have time to work through these as you work on other things? They look like pretty uncontroversial fixes.

**Comment by stevenchong** [comment]
Sure thing @amoeba .  Thanks for posting the warnings.

**Comment by stevenchong** [comment]
@amoeba Just updated `ECSO8.owl` and think I addressed all of the validation warnings.  Let me know if I missed any.

**Comment by amoeba** [comment]
Looks like you did. Thanks a bunch!

**Comment by SrishtiSingh-eu** [comment]
{"@timestamp":"2020-05-01T16:42:46.834+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"Lexical form '#2F4F4F' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.841+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"Lexical form '#696969' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.841+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"Lexical form '#A9A9A9' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.842+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"Lexical form '#808080' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.843+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"Lexical form '#000000' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.844+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"Lexical form '#C0C0C0' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.946+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"[line: 80, col: 24] Lexical form '#696969' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.947+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"[line: 80, col: 81] Lexical form '#000000' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.948+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"[line: 80, col: 138] Lexical form '#C0C0C0' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.948+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"[line: 80, col: 195] Lexical form '#2F4F4F' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.949+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"[line: 80, col: 252] Lexical form '#808080' not valid for datatype XSD hexBinary "}
{"@timestamp":"2020-05-01T16:42:46.950+02:00","level":"WARN ","thread":"main","class":"org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger", "code_line_number":"95","message":"[line: 80, col: 309] Lexical form '#A9A9A9' not valid for datatype XSD hexBinary "}

I am still getting these warnings

**Comment by amoeba** [comment]
Hi @SrishtiSingh-eu, thanks for letting us know. Can you describe how you got those warnings? Hopefully in a way I can run locally? At first glance, those warnings don't look they come from ECSO.

**Comment by SrishtiSingh-eu** [comment]
I have a String which has XML data. I get these warning when I convert it into Jena Model.
` InputStream rdfInput = new ByteArrayInputStream(data.getBytes());
Model modelResult = ModelFactory.createDefaultModel().read(rdfInput, "", "RDF/XML");
`


here is an part of the XML String data which raise warnings.

`<edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#FFE4B5</edm:componentColor><edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#FFDEAD</edm:componentColor><edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#FFFACD</edm:componentColor><edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#F5DEB3</edm:componentColor><edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#DEB887</edm:componentColor><edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#EEE8AA</edm:componentColor>`
