### ISSUE TITLE
Establish contribution guidelines for ECSO

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-ontologies#51]
We'd like folks on the datateam and elsewhere to be able to suggest new terms or changes to existing terms. Providing a way to do that here on GitHub would be great and we could send people wanting to contribute to this repo.

- Update the root README with instructions
- Consider using an Issues template to help contributors fill in enough information about the addition or change they want

**Comment by mbjones** [comment]
The template I used for [object-formats](https://github.com/DataONEorg/object-formats) might be a useful starting point.

**Comment by mpsaloha** [comment]
I was recently told that this Google sheet was being used for the purpose
of documenting "missing terms" from ECSO or EnvO, that are needed for
attribute annotation:

https://docs.google.com/spreadsheets/d/1ULEwESDbepuPs2xGKrZMyWYW7BHOLmGi4C8luPgbsrQ/edit#gid=0

...but if we want to do this somewhere else, that is fine with me.  I think
the columns in the Google sheet are good ones.

It would also be useful, as Bryce suggests, that we document suggested
revisions to existing terms, which would recommend adding a column that
might say "REVISE" with a more detailed suggestion of why the existing term
is problematic provided in the column J: NOTES.

thanks,
Mark

**Comment by mbjones** [comment]
I added CONTRIBUTING.md to describe a proposed approach in issue #89 which would cover all ontologies in this repo, including ECSO. Please review and comment in #89, and then we can close this issue with that one.

**Comment by amoeba** [comment]
Thanks @mbjones. I looked over the changes and they look good to me. Anyone feel free to re-open this if you have any comments specifically about contribution guidelines for ESCO. Otherwise, let's discuss on https://github.com/DataONEorg/sem-prov-ontologies/issues/89.
