### ISSUE TITLE
Broken Link in ProvONE Draft

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/sem-prov-ontologies#60]
I ran across a broken link in the ProvONE draft.

It looks like the href is correct, but the href target might be incorrect. Note how there's two `bib-PROVO` tags [here](https://github.com/DataONEorg/sem-prov-ontologies/blob/master/provenance/ProvONE/v1/provone.html#L4022) and line 4025.

The namespace URL for ProvONE in _Example 1_ doesn't seem to resolve for me either; http://purl.org/provone (it might supposed to be http://purl.dataone.org/provone/2015/01/15/ontology#)

**Comment by amoeba** [comment]
Thanks @ThomasThelen, good find. The duplicate `id` was fixed in ea0e4a4e2c9acd018f82f3173521e5c85a3c01b1 and the incorrect namespace prefix for ProvONE was fixed in 36e7b92ced465bc594c81140a63f88ac85e49467.
