### ISSUE TITLE
Conduct salmon data mobilization use case

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-ontologies#76]
Conduct data-mobilization use case w/ ADF&G. Could we build something to continuously mobilize data out of ADF&G. Maybe constrained to one management area or even river system

**Comment by mbjones** [comment]
This ticket was very general, and has been replaced by the more specific tasks in epic #82. So closing this. Please add any new tasks to Epic #82, and any details in general about the mobilization to that epic ticket.
