### ISSUE TITLE
document contributions model for Salmon ontology

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-ontologies#87]

**Comment by mbjones** [comment]
We need a model for how people can contribute new terms to the salmon ontology, and how we review and vet those for inclusion in a new release of the ontology. This could be as simple as a CONTRIBUTING.md file modeled on our existing ones from other repositories.

**Comment by samanthacsik** [comment]
Just gathering some useful resources to draw inspiration from (ENVO has some really well defined protocols for contributors). I see a few different options, though we may want to provide a couple different ways for editors to contribute depending on their level of familiarity (with Protégé, formalized ontology development, etc.) and the number of terms requested.

**Option 1: Request that a small number of terms (e.g. one or few terms) be added as an [Issue](https://github.com/DataONEorg/sem-prov-ontologies/issues)** 

- We will need to provide a structured template (I'm envisioning something like the metacatui [Bug Report Issue template](https://github.com/NCEAS/metacatui/issues/new?assignees=&labels=bug&template=bug_report.md&title=) for any necessary information (e.g. term label, definition, dbXref/source, parent class, comment, etc.) regarding the requested term. 

**Option 2: Ask contributors to use GitHub's [fork-and-pull](https://gist.github.com/Chaser324/ce0505fbed06b947d962) approach**

- This may be appropriate for contributors who already have familiarity with Protege/formal ontology development and who may want to add many terms. Opening a line of communication/discussion via a GitHub issue prior to submitting a PR is likely important. See ENVO's [Steps for contributions by non-editors](https://github.com/EnvironmentOntology/envo/wiki/Adding-classes-to-ENVO#steps-for-smaller-contributions-by-non-editors) for well-detailed steps.

- *NOTE:* This would also require that we have a detailed description of our design pattern for contributors to follow.

**Option 3: Provide a .csv template, which we can ingest into Protégé**

- See ENVO's [Robot template & tutorial](https://github.com/EnvironmentOntology/envo/wiki/ENVO-Robot-template-and-merge-workflow) or [Protégé's Cellfi plugin](https://github.com/protegeproject/cellfie-plugin/wiki/Grocery-Tutorial) as two potential options to explore.

**Comment by mbjones** [comment]
@samanthacsik These all sound like good ideas. For all three options, I think it would be good to have an open issue to discuss and refine terminology proposals. We have an issue template for object format additions to the DataONE formats vocabulary that might be useful as a guide. Here's an example for the GeoJSON format proposal: https://github.com/DataONEorg/object-formats/issues/16

**Comment by mbjones** [comment]
I started a CONTRIBUTING.md file describing how to contribute to the ontology work in issue #89 -- please continue discussion there, and bring any of the ideas along from this thread that are needed. I will leave this open until we've had a chance to migrate ideas, but this should be closed along with #89 when ready.

**Comment by mbjones** [comment]
Completed with #89 , so closing this issue. If further changes/additions to CONTRIBUTING guidelines are needed, please open a new issue.
