### ISSUE TITLE
add contribution guidelines

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-ontologies#89]
It is unclear how the ECSO and other ontologies are managed and what contributions are made. Add an appropriate description, based on discussions with @mpsaloha and @mobb.  While I'm at it, set up our starndard branch structure for contributions, using `main` and `develop` branches.

**Comment by mbjones** [comment]
The default branch has been renamed!

`master` is now named `main`

If you have a local clone, you can update it by running:

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by mbjones** [comment]
Added an initial CONTRIBUTING.md file, with our standard `main` and `develop` workflow for releases, and branch protections for `main`. New features (like the MOSAIC ontology and SALMO ontology) should be developed on feature branches that are branched from `develop`, and should be named using the issue number for the issue they are targeting. For example, I created `feature-88-mosaic` and `feature-49-salmon-ontology` for the two new development threads, respectively. These replace earlier branches for those projects.  

@amoeba @mpsaloha @mobb Let's review and discuss CONTRIBUTING.md and see what we think should be changed before we finalize a model.

**Comment by amoeba** [comment]
Looks fine to me, @mbjones. Thanks for taking the initiative to get this set up. Once people get sync'd up with GitHub, I think we can do a pass over the existing branches and do some much-needed cleanup.

@samanthacsik I think a branch or two have been renamed for which you might have had uncommited or unpushed changes so let's touch base when you're ready to send your latest changes up to make sure they get put in the right place and we don't lose anything.

I'll leave this open for now for others to comment.

**Comment by amoeba** [comment]
Closing since no comments have come in the last week. If you do have any comments, please feel free to comment and we can re-open. Thanks for adding this @mbjones.
