### ISSUE TITLE
Expand purl.dataone.org redirect for ECSO

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-ontologies#90]
@mpsaloha was looking for a stable, resolve-able URI for ECSO today and we don't really have one. This gap exists for, I think, all of our ontologies. We've talked about eventually having a centralized home for all ontologies but, until then, I think we can incrementally improve what we have in place now and go from there.

We have a redirect for ECSO URIs over to BioPortal set up on purl.dataone.org so things like https://purl.dataone.org/odo/ECSO_00001234 resolve to appropriate BioPortal pages for the term. But https://purl.dataone.org/odo/ECSO_ and https://purl.dataone.org/odo/ECSO currently resolve to a 404. At a very minimum, we could have the latter two URIs resolve to the BioPortal landing page. Later on down the line, we might change where any of these point and this gives us flexibility.

- [ ] Update our purl.dataone.org redirects so https://purl.dataone.org/odo/ECSO_  and https://purl.dataone.org/odo/ECSO resolve to https://bioportal.bioontology.org/ontologies/ECSO/

**Comment by amoeba** [comment]
Issue created on dataone_purl at https://github.com/DataONEorg/dataone_purl/issues/6 and change PR'd in https://github.com/DataONEorg/dataone_purl/pull/7.

I think @mpsaloha is good on this change. @mbjones does this seem okay to you?

**Comment by mbjones** [comment]
@amoeba Overall this looks good to me. So, does this mean that the namespace for ECSO ends in an underscore? Is that what we want? And is it the same pattern used by OBO Foundry for namespaces for their numerically identified terms?

**Comment by amoeba** [comment]
Yeah, I think that's the right take and, as far as I can tell, this all matches the [OBO Foundry policy](http://www.obofoundry.org/id-policy). The way I read it, our "IDSPACE" for ECSO is `http://purl.dataone.org/odo/ECSO` and Foundry-compliant URIs follow this form:

FOUNDRY_OBO_URI ::= "http://purl.obolibrary.org/obo/" IDSPACE "_" LOCALID

which leads to ECSO:00001234 being the natural shorthand our URIs which means the namespace prefix is `http://purl.dataone.org/odo/ECSO_`.

And following their policy on the "Home page" for an ontology, this change aligns us with the policy which states that the IDSPACE should resolve to a home page for the ontology.

One thing we're not doing which does align with the policy is resolve an OWL file for the ontology at IDSPACE.owl (e.g., http://purl.dataone.org/odo/ECSO.owl). One problem I see here is that, at some point, the ontology IRI (in the OWL file) changed to http://purl.dataone.org/odo/ECSO8.owl (note the 8) when I think it should have been kept http://purl.dataone.org/odo/ECSO.owl (no 8). I haven't looked into when or when that change was made.

**Comment by mbjones** [comment]
Sounds good. And, yeah, we should rename it ECSO.owl. I think that was simply an artifact of filename versioning rather than using source code control for versioning. I don't think it was ever released that way, but a `git mv` will preserve the history links between the filenames. Thanks Bryce.

**Comment by amoeba** [comment]
Sounds good. I've added a note about this to the checklist at the top of https://github.com/DataONEorg/sem-prov-ontologies/issues/41 (Release ECSO 0.10 issue) so it gets handled at that point.

**Comment by amoeba** [comment]
These are live.

- https://purl.dataone.org/odo/ECSO
- https://purl.dataone.org/odo/ECSO_

Both redirect to BioPortal.
