### ISSUE TITLE
Deal with two KWG URIs in the MOSAiC ontology

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-ontologies#99]
We found that two MOSAiC URIs used the KWG URI prefix:

- http://purl.dataone.org/odo/KWG_Hazards_00000225
- http://purl.dataone.org/odo/KWG_Hazards_00000226

These were released in v1.0.0. @mpsaloha says there are some spaces in the MOSAiC URI space so we can fill in two gaps with these. I'm not sure yet how we should handle this: Do we deprecate the two URIs above or something? I'll look into it.

**Comment by amoeba** [comment]
In the ontology, we reference these URIs with the following triples:

http://purl.dataone.org/odo/KWG_Hazards_00000225

```
<http://purl.org/dc/elements/1.1/creator> <http://orcid.org/0000-0003-0632-7576> .
<http://purl.org/dc/elements/1.1/date> "2021-05-05T06:11:27Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#NamedIndividual> .
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://purl.dataone.org/odo/MOSAIC_00000022> .
<http://www.w3.org/2000/01/rdf-schema#label> "MOSAiC"@en .
<http://www.w3.org/2002/07/owl#sameAs> <http://purl.dataone.org/odo/KWG_Hazards_00000226> .
```

http://purl.dataone.org/odo/KWG_Hazards_00000226

```
<http://purl.org/dc/elements/1.1/creator> <http://orcid.org/0000-0003-0632-7576> .
<http://purl.org/dc/elements/1.1/date> "2021-05-05T06:12:04Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#NamedIndividual> .
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://purl.dataone.org/odo/MOSAIC_00000022> .
<http://www.w3.org/2000/01/rdf-schema#label> "Multidisciplinary drifting Observatory for the Study of Arctic Climate"@en .
<http://www.w3.org/2002/07/owl#sameAs> <https://purl.dataone.org/odo/MOSAIC_00000023> .

```

**Comment by mpsaloha** [comment]
Those two terms have a mis-minted prefix, and their numerical parts are not
yet taken up in the MOSAIC namespace.
Solution:  global edit of "KWG_Hazards" to "MOSAIC"

Mark

**Comment by amoeba** [comment]
We decided to simply edit the prefix to the correct one. I'm not really sure if that's the best thing but it's probably not very very problematic because (1) these were named individuals and not, say, classes and (2) the ontology isn't really out in the wild yet.
